import { type NextPage } from "next";
import Head from "next/head";

import URLShortener from "@/components/URLShortener";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <h1 className="text-3xl text-center font-bold tracking-tighter text-amber-100 md:text-5xl">
          URL Shortener
        </h1>
        <URLShortener />
      </div>
    </>
  );
};

export default Home;
