import Head from "next/head";
import ShortCount from "@/components/Shorten/ShortCount";
import URLShortener from "@/components/Shorten/URLShortener";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <h1 className="text-center text-3xl font-bold tracking-tighter text-amber-100 md:text-5xl">
          URL Shortener
        </h1>
        <ShortCount />
        <URLShortener />
      </div>
    </>
  );
};

export default Home;
